# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Study
email: 
description:  linux_base, C language,...
baseurl:
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  icarus1513

# Build settings
markdown: kramdown
